variables:
  azureContainerRegistry: aibekshulembekov.azurecr.io
  azureSubscriptionEndpoint: Azure Resource Group
stages:
- stage: Build and Push
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build services
    steps:
    - task: DockerCompose@0
      displayName: Build services
      inputs:
        action: Build services
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: docker-compose.yml
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)
  - job: Push
    displayName: Push services
    steps:
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        action: Push services
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: docker-compose.yml
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)
- stage: Run
  displayName: Run stage
  jobs:
  - job: Run
    displayName: Run services
    steps:
    - task: DockerCompose@0
      displayName: Run services
      inputs:
        action: Run services
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: docker-compose.ci.build.yml
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        buildImages: true
        abortOnContainerExit: true
        detached: false

