variables:
  azureContainerRegistry: aibekshulembekov.azurecr.io
  azureSubscriptionEndpoint: Azure Resource Group
stages:
- stage: Run
  displayName: Run and push stage
  jobs:
  - job: Run
    displayName: Run docker-compose
    steps:
    - task: DockerCompose@0
      displayName: Container registry login
      inputs:
        containerregistrytype: Azure Container Registry
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)
    - task: DockerCompose@0
      displayName: Run a Docker Compose command
      inputs:
        action: Run a Docker Compose command
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: docker-compose.yml 
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        dockerComposeCommand: rm